apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "{{ .Values.env.telegramBotToken }}"
            - name: TELEGRAM_CHAT_ID
              value: "{{ .Values.env.telegramChatId }}"
            - name: BINANCE_API_KEY
              value: "{{ .Values.env.binanceApiKey }}"
            - name: BINANCE_API_SECRET
              value: "{{ .Values.env.binanceApiSecret }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}