apiVersion: v2
name: notification-bot
description: A Helm chart for Binance notification bot
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - binance
  - notifications
  - telegram
  - crypto
home: https://github.com/SusterJiri/NotificationBot
sources:
  - https://github.com/SusterJiri/NotificationBot
maintainers:
  - name: SusterJiri
    email: your-email@example.com